### ISSUE TITLE
Recording download failure should not save "not found" file

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-web#122]
https://github.com/rh-jmc-team/container-jfr-web/pull/118#issuecomment-675132342

When the user attempts to download a recording and the download fails (ex. another client has deleted the recording but the first client's web-client data is out of date), the user receives a "foo.jfr" file with the contents "foo not found". This should instead cause an error notification to be displayed and no file to be downloaded.

**Comment by vic-ma** [comment]
After #116, I don't get this problem anymore, so I think it's fixed.

The report still downloads, but that download never gave an error in the first place and is the actual valid report, so I'm not sure if that's something we have to worry about.
