### ISSUE TITLE
[design] Recording's options (max age, max size, toDisk) should be discoverable

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-web#127]
The API responses from `/api/v1/targets/:targetId/recordings` includes details on each recording about their maxAge/maxSize/toDisk option settings, but there is no UI element that exposes this information to the user. Since #103 adds a way for users to customize these settings and change their values from the defaults when a recording is created, there should also be a corresponding way for the user to see the values of these settings for each recording.

**Comment by Alexjsenn** [comment]
Would it make sense to add this information in the popdown area of each recording, above the report?

**Comment by andrewazores** [comment]
Yea, that seems like a good way to go about it. Maybe add some kind of sections or dividers within the collapsed panel so that there is a "Recording Options" or "Attributes" heading and an "Automated Analysis" heading above each, if that makes sense.

**Comment by Alexjsenn** [comment]
![Screenshot from 2020-09-18 16-10-07](https://user-images.githubusercontent.com/28233112/93640985-84cd2100-f9c9-11ea-89b3-f768ce29db74.png)

**Comment by Alexjsenn** [comment]
I had difficulty making the section titles larger, or maybe they should be bold or something? Im not very sure.

**Comment by andrewazores** [comment]
I think that's fine, the size looks similar to the main items in the recording row (name, start timestamp, duration, status) and the table heading. I don't think that the options and analysis headings should be larger or bolder than those.

**Comment by Alexjsenn** [comment]
Yeah, the "Java Application" and those titles are super large, but it definitely makes sense that those headers shouldn't be larger than the main items!

**Comment by andrewazores** [comment]
The titles like "Java Application", "JVM Internals", etc. come from the automated analysis report produced by a thin wrapper around a JMC implementation: https://github.com/rh-jmc-team/container-jfr-core/blob/main/src/main/java/com/redhat/rhjmc/containerjfr/core/reports/ReportGenerator.java

Although we do have a mechanism for modifying these reports (https://github.com/rh-jmc-team/container-jfr-core/blob/main/src/main/java/com/redhat/rhjmc/containerjfr/core/reports/ReportTransformer.java), so we could use that to transform ex. `<h1>` tags to `<h3>` tags, or whatever produces an appropriate appearance.
