### ISSUE TITLE
Internal Server Error after View in Grafana & Download action

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/container-jfr-web#32]
In a CRC instance with the operator deployed, I can reproduce an internal server error when creating a recording for some application, clicking 'View in Grafana' and then clicking 'Download'.

**Comment by andrewazores** [comment]
Hmm. We have a bug in container-jfr where the Grafana upload causes the in-memory recording to be closed (deleted).

For the purposes of your demo you can work around this by saving the recording to the archives first. This copy will survive after being uploaded to Grafana, so you can download the recording to your local machine after.

**Comment by andrewazores** [comment]
Closing this one in favour of the above linked bug, since this is a backend problem.
