### ISSUE TITLE
Support using jfc profiles from the JDK

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/container-jfr-web#34]
The JVM ships default and profile jfc files (e.g. in Fedora openjdk11: lib/jfr/<name>.jfc)

JMC UI supports selecting either of these. The UI should also allow users to select either of these when configuring a recording

**Comment by andrewazores** [comment]
This seems trickier than it sounds. The set of predefined profiles available to the container-jfr JVM are unrelated to the set of profiles available on the target JVM. Not sure if there is a nice way to ask the remote target JVM what its supported profiles are.

**Comment by jiekang** [comment]
Yeah I'd definitely be looking at trying to use the profiles from the target JVM. I'll have to check how JMC behaves but I feel like it is able to do that.

**Comment by andrewazores** [comment]
Backend support for this is in progress: rh-jmc-team/container-jfr#140

**Comment by andrewazores** [comment]
See also:

rh-jmc-team/container-jfr#141

rh-jmc-team/container-jfr#142

**Comment by andrewazores** [comment]
Backend support is now merged and it's already possible to select a template using the existing event specifier string with new `template=Foo` syntax. Closing this issue - #47 will track development of a more specific UI for templates.
