### ISSUE TITLE
Support user-inputted times

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/container-jfr-web#35]
The UI allows selection from a list of times. Instead it should allow users to input a time; something like:

time := \<number\>\<unit\> | 'unlimited'

number in set of Integers greater than 0
unit in {s, m, h, d}

e.g.

5s
30m
2h
1d
etc.

**Comment by andrewazores** [comment]
@jiekang do you think the input should be simply a text field, which then does some validation to ensure that the input looks like `[\\d]+[mdhs]`? How about ex. a number spinner plus a units dropdown?

**Comment by jiekang** [comment]
I personally prefer a text field. I find it significantly faster than any options that use a mouse... I'd prefer text first and then have an option to also select via other ux afterwards.

**Comment by jiekang** [comment]
But to be honest, if a patch comes that adds it via spinner + units selection, I'm not going to complain hahah :P

**Comment by jiekang** [comment]
Damn just notice \< and \> need to be escaped to be visible... oops.

**Comment by andrewazores** [comment]
Well a number spinner and unit dropdown would still be keyboard navigable if set up properly, using `<Tab>` to switch focus to them. The spinner should still allow keyboard numeric input, and dropdowns do also generally allow keyboard input for selecting matching entries.

**Comment by jiekang** [comment]
Okay, I can see the unit dropdown. How does the number spinner handle input with variable number of digits? Maybe what I think of for number spinner is not what you're thinking of heh;;

**Comment by andrewazores** [comment]
Like this: https://jqueryui.com/spinner/

**Comment by jiekang** [comment]
Oooh.... what I envisioned is not the same; more like the date selection thing where each digit can spin from 0-9. That looks good to me!
