### ISSUE TITLE
[react] Tab sets should have consistent widths

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr-web#76]
Tabsets are used in various pieces of the React rewrite of the Web client. We need to decide if these should span the width of the container (card) in all cases, or if they should only be as wide as needed for each tab title. Then all tabsets should be made consistent in their widths.

![image](https://user-images.githubusercontent.com/3787464/81440970-6c6a1180-9160-11ea-866c-4136b210a5ed.png)
![image](https://user-images.githubusercontent.com/3787464/81440977-712ec580-9160-11ea-9aee-f182815a64b7.png)
![image](https://user-images.githubusercontent.com/3787464/81441091-aa673580-9160-11ea-8f99-1fb54360988e.png)

**Comment by Alexjsenn** [comment]
I think it looks overall cleaner to have the tabs be only the necessary width to accomodate the title. Having them span the whole width looks strange when opened on a browser on a large screen. Does this make sense?

**Comment by andrewazores** [comment]
Sounds reasonable. I would check if Patternfly has any guidelines laid out for when to use each option, but if there is no guidance or it could go either way then we can go with that.

**Comment by Alexjsenn** [comment]
I couldn't find anything specific from Patternfly, but It is the default layout they provide, so I think it makes sense.
